language: java
sudo: true
before_install:
- chmod +x mvnw
jdk:
- openjdk8
script: mvn clean install
deploy:
  provider: heroku
  api_key:
    secure: gDnpVt/VrsNHrl0PUnaSRcx+bB/s06w1rw/abS22Y9jOECzA7NvPMRSSjjlmq8dQVovYzW1xHRKCJIUT2acl52uisLwEuT/8BJCXmI41vdW1CTN5rv4YxCQiaZnoID23+CD4OuL7ZYvxbuumeHuBqYSAzvVKW1zPGy2THQf6jnYyH6G7w3LGwT6+0JGu/n12tblX0AMq9B9O2XbR/O/OF9RWB0vFVQwsQdKs6p/HnbVgYk/CkcAo8PpdZcIsIGSt3xXAKVc61FmK+KgSDZ/V4rQ59SAgTKTb1JO8qng19CpqTUubvqTXZO1pDG+1vcYRGmL7fRSvKe/9mgilQMdhOnPvMRFj4PS0ePQ8H3eO00zYeruxG1o0WnOo0gejsaggAH/aVxwkSOkxI8l/asSGPOGlvwxZ6GDn2KPiCnSwZgTrcMKkVQlZSL4zU9n2fpxXomvmHT7LOLKTqKDp4zxySAPFz/kzup74fEm4z/1GTLP1MbUHni9b/6PTOQZs+ENAn5VQAe3Bup5jVFXGU8RPTLPwQQiu2168SfcpOhaxqNQA0pov9RZJ3TkYd6fLS5nVU5HbONNSyS3ynVlq0VujgDEkq+BmIStZQIEfnEAcD5s4ObnLLoAUAPbvfWBpBv+BdUvkk3U32ThtkFIdEgd4DjxSBDt1FRonWgWXo1WMUKc=
  app: travis-ci-example
